// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using FlatRockTechnology.OnlineMarket.DataAccessLayer.Database.Abstractions;
using System;
using System.Collections.Generic;

namespace FlatRockTechnology.OnlineMarket.DataAccessLayer.DB
{
    public partial class ProductCategory : IEntity
    {
        public Guid Id { get; set; }
        public Guid? ProductId { get; set; }
        public Guid? SubCategoryId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public Guid? ModifiedBy { get; set; }

        public virtual User CreatedByNavigation { get; set; }
        public virtual User ModifiedByNavigation { get; set; }
        public virtual Product Product { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}