// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using FlatRockTechnology.OnlineMarket.DataAccessLayer.Database.Abstractions;
using System;
using System.Collections.Generic;

namespace FlatRockTechnology.OnlineMarket.DataAccessLayer.DB
{
    public partial class User : IEntity
    {
        public User()
        {
            AddressCreatedByNavigation = new HashSet<Address>();
            AddressModifiedByNavigation = new HashSet<Address>();
            AddressUser = new HashSet<Address>();
            CategoryCreatedByNavigation = new HashSet<Category>();
            CategoryModifiedByNavigation = new HashSet<Category>();
            InverseModifiedByNavigation = new HashSet<User>();
            OrderCreatedByNavigation = new HashSet<Order>();
            OrderModifiedByNavigation = new HashSet<Order>();
            OrderProductCreatedByNavigation = new HashSet<OrderProduct>();
            OrderProductModifiedByNavigation = new HashSet<OrderProduct>();
            OrderUser = new HashSet<Order>();
            ProductCategoryCreatedByNavigation = new HashSet<ProductCategory>();
            ProductCategoryModifiedByNavigation = new HashSet<ProductCategory>();
            ProductCreatedByNavigation = new HashSet<Product>();
            ProductModifiedByNavigation = new HashSet<Product>();
            SubCategoryCreatedByNavigation = new HashSet<SubCategory>();
            SubCategoryModifiedByNavigation = new HashSet<SubCategory>();
            UserRole = new HashSet<UserRole>();
        }

        public Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string NormalizedEmail { get; set; }
        public bool? IsEmailConfirmed { get; set; }
        public string UserName { get; set; }
        public string NormalizedUserName { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public string City { get; set; }
        public bool? IsDisabled { get; set; }
        public bool? IsActive { get; set; }
        public string PhoneNumber { get; set; }
        public DateTime? CreatedAt { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public Guid? ModifiedBy { get; set; }
        public string PasswordRecoveryCode { get; set; }

        public string EmailVerificationCode { get; set; }

        public virtual User ModifiedByNavigation { get; set; }
        public virtual ICollection<Address> AddressCreatedByNavigation { get; set; }
        public virtual ICollection<Address> AddressModifiedByNavigation { get; set; }
        public virtual ICollection<Address> AddressUser { get; set; }
        public virtual ICollection<Category> CategoryCreatedByNavigation { get; set; }
        public virtual ICollection<Category> CategoryModifiedByNavigation { get; set; }
        public virtual ICollection<User> InverseModifiedByNavigation { get; set; }
        public virtual ICollection<Order> OrderCreatedByNavigation { get; set; }
        public virtual ICollection<Order> OrderModifiedByNavigation { get; set; }
        public virtual ICollection<OrderProduct> OrderProductCreatedByNavigation { get; set; }
        public virtual ICollection<OrderProduct> OrderProductModifiedByNavigation { get; set; }
        public virtual ICollection<Order> OrderUser { get; set; }
        public virtual ICollection<ProductCategory> ProductCategoryCreatedByNavigation { get; set; }
        public virtual ICollection<ProductCategory> ProductCategoryModifiedByNavigation { get; set; }
        public virtual ICollection<Product> ProductCreatedByNavigation { get; set; }
        public virtual ICollection<Product> ProductModifiedByNavigation { get; set; }
        public virtual ICollection<SubCategory> SubCategoryCreatedByNavigation { get; set; }
        public virtual ICollection<SubCategory> SubCategoryModifiedByNavigation { get; set; }
        public virtual ICollection<UserRole> UserRole { get; set; }
    }
}