// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using FlatRockTechnology.OnlineMarket.DataAccessLayer.Database.Abstractions;
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace FlatRockTechnology.OnlineMarket.DataAccessLayer.Database
{
    public partial class User : IdentityUser, IEntity
    {
        public User()
        {
            AddressCreatedByNavigation = new HashSet<Address>();
            AddressModifiedByNavigation = new HashSet<Address>();
            AddressUser = new HashSet<Address>();
            CategoryCreatedByNavigation = new HashSet<Category>();
            CategoryModifiedByNavigation = new HashSet<Category>();
            InverseCreatedByNavigation = new HashSet<User>();
            InverseModifiedByNavigation = new HashSet<User>();
            OrderCreatedByNavigation = new HashSet<Order>();
            OrderModifiedByNavigation = new HashSet<Order>();
            OrderProductCreatedByNavigation = new HashSet<OrderProduct>();
            OrderProductModifiedByNavigation = new HashSet<OrderProduct>();
            OrderUser = new HashSet<Order>();
            ProductCategoryCreatedByNavigation = new HashSet<ProductCategory>();
            ProductCategoryModifiedByNavigation = new HashSet<ProductCategory>();
            ProductCreatedByNavigation = new HashSet<Product>();
            ProductModifiedByNavigation = new HashSet<Product>();
            SubCategoryCreatedByNavigation = new HashSet<SubCategory>();
            SubCategoryModifiedByNavigation = new HashSet<SubCategory>();
        }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string City { get; set; }
        public bool? IsDisabled { get; set; }
        public DateTime? CreatedAt { get; set; }
        public string? CreatedBy { get; set; }
        public DateTime? ModifiedAt { get; set; }
        public string? ModifiedBy { get; set; }

        public virtual User CreatedByNavigation { get; set; }
        public virtual User ModifiedByNavigation { get; set; }
        public virtual ICollection<Address> AddressCreatedByNavigation { get; set; }
        public virtual ICollection<Address> AddressModifiedByNavigation { get; set; }
        public virtual ICollection<Address> AddressUser { get; set; }
        public virtual ICollection<Category> CategoryCreatedByNavigation { get; set; }
        public virtual ICollection<Category> CategoryModifiedByNavigation { get; set; }
        public virtual ICollection<User> InverseCreatedByNavigation { get; set; }
        public virtual ICollection<User> InverseModifiedByNavigation { get; set; }
        public virtual ICollection<Order> OrderCreatedByNavigation { get; set; }
        public virtual ICollection<Order> OrderModifiedByNavigation { get; set; }
        public virtual ICollection<OrderProduct> OrderProductCreatedByNavigation { get; set; }
        public virtual ICollection<OrderProduct> OrderProductModifiedByNavigation { get; set; }
        public virtual ICollection<Order> OrderUser { get; set; }
        public virtual ICollection<ProductCategory> ProductCategoryCreatedByNavigation { get; set; }
        public virtual ICollection<ProductCategory> ProductCategoryModifiedByNavigation { get; set; }
        public virtual ICollection<Product> ProductCreatedByNavigation { get; set; }
        public virtual ICollection<Product> ProductModifiedByNavigation { get; set; }
        public virtual ICollection<SubCategory> SubCategoryCreatedByNavigation { get; set; }
        public virtual ICollection<SubCategory> SubCategoryModifiedByNavigation { get; set; }
        Guid IEntity.Id { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }
    }
}